name: Deploy Github Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: $${{ secrets.GITHUB_TOKEN }}
      - name: Configure github pages
        uses: actions/configure-pages@v3
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1



